---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: meshplay
    component: operator
  name: meshplay-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshplay-operator
  namespace: meshplay
  labels:
    app: meshplay
    component: operator
spec:
  selector:
    matchLabels:
      app: meshplay
      component: operator
  replicas: 1
  template:
    metadata:
      labels:
        app: meshplay
        component: operator
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: meshplay-operator
      containers:
      - name: manager
        image: khulnasoft/meshplay-operator:stable-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9443
          name: server
          hostPort: 9443
        - containerPort: 8080
          name: metrics
          hostPort: 8080
        command:
        - /manager
        args:
        - --enable-leader-election
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
