apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: meshplay-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshplay-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: meshplay-operator-role
rules:
- apiGroups:
  - meshplay.khulnasoft.com
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meshplay.khulnasoft.com
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshplay-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: meshplay-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: meshplay-leader-election-role
subjects:
- kind: ServiceAccount
  name: meshplay
  namespace: meshplay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshplay-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshplay-operator-role
subjects:
- kind: ServiceAccount
  name: meshplay
  namespace: meshplay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meshplay-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meshplay-proxy-role
subjects:
- kind: ServiceAccount
  name: meshplay
  namespace: meshplay
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meshplay
    component: operator
  name: meshplay-operator-metrics-service
  namespace: meshplay
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: meshplay
    component: operator
